### ISSUE TITLE
Update Testimonials Code To Use Hakyll Public API

### ISSUE THREAD

**Issue by rebeccaskinner** [haskell-infra/www.haskell.org#109]
Note: Depends on https://github.com/haskell-infra/www.haskell.org/issues/108

We should update the implementation of the testimonials code to no longer use hakyll internal modules.

**Comment by philderbeast** [comment]
@rebeccaskinner is this still an issue? If so, what would the fix involve?

**Comment by rebeccaskinner** [comment]
@philderbeast I don't think it's an issue anymore. I'm not sure when we fixed this but I suspect a while ago and we just forgot to link this issue. It looks like your PR #306 also addresses the updates, so I'm going to close this issue and also approve that PR.
