### ISSUE TITLE
Download page is confusing

### ISSUE THREAD

**Issue by hasufell** [haskell-infra/www.haskell.org#12]
https://www.haskell.org/downloads/ is confusing

* it doesn't concisely present the most popular options, but instead directs to haskell-platform, which then might direct to your packager manager, ghcup or other things, which creates another layer of confusing indirection
* "minimal installer" is a duplicate of haskell-platforms redirection to system package managers
* the description of haskell-platform "Installs GHC, Cabal, and some other tools, along with a starter set of libraries in a global location on your system." is inaccurate for choices like ghcup, which does not install in a global location
* it doesn't direct to chocolatey, which is considered the most properly packaged GHC for windows, according to some, although its popularity is surprisingly low according to the haskell 2019 survey (which might be a good reason to have it on the download page)

**Comment by mattbaumann** [comment]
I agree, it is very confusing, probably it ballooned over time a bit.

Suggested Layout:

1. Contents
2. Platform Installer Links (for beginners) + chocolatey
3. Advanced Installation
  1. Stack
  2. Additional Libraries
4. Need Help? -> Link to Help Page.

Following sections should be deleted:
1. Minimal Installer
2. Where you can get help (should get own page)

Unfortunately is the https://wiki.haskell.org/Distributions Page, which is the first section  another of those broken pages. It is a page about _IDE's_ unlike the title suggests wrongfully. It does not mention IntelliJ for example. This page has to be refactored too.

**Comment by hasufell** [comment]
> Platform Installer Links (for beginners) + chocolatey

Do we still need the Haskell Platform links if windows users should prefer to use Chocolatey? For linux and BSD, there are distro packages, binary distribution (the tarballs) and ghcup.

> Advanced Installation

What would this section be?

> Stack

This is an advanced tool like nix that can be used with haskell. Albeit its popularity, does it belong on the download page or should this rather be linked to as a project management tool?

**Comment by mattbaumann** [comment]
I agree with you on this one, hmm. Unfortunately, as you can see there is not much traffic on this repository, so there is not really an open group discussion here, except us.

Why not, I'll produce a pull request in the upcoming days with your and mine changes, if that's alright, and normally people start a discussion as soon as there is an request. So hang on and keep the discussion up as soon as my pull request is available. Thanks for the suggestion by the way.

**Comment by AMDphreak** [comment]
> I agree with you on this one, hmm. Unfortunately, as you can see there is not much traffic on this repository, so there is not really an open group discussion here, except us.
> 
> Why not, I'll produce a pull request in the upcoming days with your and mine changes, if that's alright, and normally people start a discussion as soon as there is an request. So hang on and keep the discussion up as soon as my pull request is available. Thanks for the suggestion by the way.

I just made a post for this without realizing it was already a topic. I made suggestions for how to address the readability of the page.

#21

**Comment by hasufell** [comment]
@mattbaumann Have you had time to create such a PR?

**Comment by mattbaumann** [comment]
Yes, I did under #14 with the intention of getting initial feedback. But since, month nobody of @haskell worked at the PR's. I don't know why, I sent an urgent EMail to inform them about my PR, but still they don't care.

**Comment by bgamari** [comment]
I can't speak for everyone when I see something in draft state I assume it is not yet ready for review.

**Comment by mattbaumann** [comment]
Ok, made it open for review, maybe that helps.

**Comment by mattbaumann** [comment]
Ok, made it open for review, maybe that helps.

**Comment by hasufell** [comment]
https://www.reddit.com/r/haskell/comments/jqtmx5/difference_between_downloading_haskell_through/?utm_source=share&utm_medium=web2x&context=3

**Comment by ketzacoatl** [comment]
Should this be closed as "Won't Fix", or what are the next steps for resolving this issue?
