### ISSUE TITLE
Is the Yesod book really introductory?

### ISSUE THREAD

**Issue by noughtmare** [haskell-infra/www.haskell.org#120]
The "Developing Web Applications with Haskell and Yesod" book is currently listed under "Introductory Books for Learning Haskell", but the book itself states that it is not suitable for complete beginners:

> This book takes as an assumption that you are already familiar with most of the basics of Haskell. There are two wonderful books for learning Haskell, both of which are available for reading online:
> * Learn You a Haskell for Great Good!
> * Real World Haskell

~https://www.yesodweb.com/book/haskell

Perhaps it should be moved to the intermediate books section?

**Comment by tomjaguarpaw** [comment]
Thanks for the report! I'm happy with your proposed solution.
