### ISSUE TITLE
Create permanent urls to latest hackage package documentation

### ISSUE THREAD

**Issue by malteneuss** [haskell-infra/www.haskell.org#133]
For frequently used Haskell packages, i like to bookmark the documentation pages. That's why i would like to propose having urls pointing to the newest hackage package documentation version. Currently, urls contain the package version like
```
https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-Traversable.html
```
I know there is the possibility to remove the version number from the url like
```
https://hackage.haskell.org/package/base/docs/Data-Traversable.html
```
but this needs manual work when bookmarking and redirects back to an url with a  package version. So the bookmarked url and the page url are never the same, so you can't see which hackage page is already bookmarked, and everytime a package updates, it requires manual new bookmarks (this is not frequent with stable `base` packages, but painful with newer, still evolving packages).

Instead it would be good to have permanent urls like
```
https://hackage.haskell.org/package/base-latest/docs/Data-Traversable.html (preferred)
https://hackage.haskell.org/package/base/latest/docs/Data-Traversable.html
```
that don't redirect like for `ghc` documentation, e.g. `https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/exts/template_haskell.html`. Those urls could be promoted in search engines to avoid having long outdated package versions showing up in the top results.

**Comment by tomjaguarpaw** [comment]
Hello @malteneuss, this issue tracker is for the website on <http://www.haskell.org>. For Hackage I believe you want the issue tracker at https://github.com/haskell/hackage-server/issues.

**Comment by malteneuss** [comment]
Alright. I've opened a ticket there: https://github.com/haskell/hackage-server/issues/979
