### ISSUE TITLE
GHC downloads page for 9.2.1 seems "messed up"

### ISSUE THREAD

**Issue by googleson78** [haskell-infra/www.haskell.org#141]
The `Source Distribution` section seems to have moved and "taken up all of the space". I've attached two screenshots, as it's much easier than describing.
9.0.1
![2021-11-02-143519_1920x1200_scrot](https://user-images.githubusercontent.com/8667384/139852973-1587ac39-76a0-499d-bb74-07def0b6eaac.png)
9.2.1
![2021-11-02-143516_1920x1200_scrot](https://user-images.githubusercontent.com/8667384/139852959-7b96af60-cd90-4044-af76-d6cc328f8117.png)

**Comment by tomjaguarpaw** [comment]
I think Ben Gamari is the one who can sort this out.

**Comment by googleson78** [comment]
Moved to https://gitlab.haskell.org/ghc/ghc/-/issues/20605
