### ISSUE TITLE
Make haskell-platform page redirect to the downloads page

### ISSUE THREAD

**Issue by MorrowM** [haskell-infra/www.haskell.org#147]
Now that the Downloads page is in decent shape I think it might be time to remove the page for the Haskell Platform and make it redirect to the downloads page. As of the time of posting haskell-platform supersedes the downloads page in the search results for "install haskell" on both Google and DuckDuckGo. I've seen a number of people struggling with their GHC/cabal installations because of this, and they end up switching to GHCup anyways, which wastes their time.

A less extreme measure would be to put a deprecation banner up, but that wouldn't be a very smooth experience for newcomers in my opinion. 

![image](https://user-images.githubusercontent.com/69002988/145032245-1ba45c12-646a-4422-9cff-2a3766bc2e6e.png)

**Comment by tomjaguarpaw** [comment]
Thanks very much for reporting this. I agree. There is some related discussion in https://github.com/haskell-infra/www.haskell.org/issues/136#issuecomment-944288891

**Comment by tomjaguarpaw** [comment]
Fixing that will close this issue too: https://github.com/haskell-infra/haskell-admins/issues/4

**Comment by tomjaguarpaw** [comment]
Fixed by https://github.com/haskell-infra/www.haskell.org/pull/149#issuecomment-997019362
