### ISSUE TITLE
Documentation page, paid resources, blessed material

### ISSUE THREAD

**Issue by ffaf1** [haskell-infra/www.haskell.org#155]
I checked the [documentation page](https://www.haskell.org/documentation/) on haskell.org and I would propose a couple of changes:

- have a `[$]` for *non gratis* books, courses, etc. This would immediately help users who cannot afford or do not will to fork cash to skim the page.
- Have a brief introductory paragraph with 1–3 (no more!) suggested courses for beginners. This would immediately improve usability for newbies and tremendously help onboarding. I would suggest *CIS 194* as such suggested resource, as it is thorough, produced neatly, gratis and has exercise.

If people agree with these goals I can make PRs.

**Comment by tomjaguarpaw** [comment]
I think both suggestions sound great! I think the first one would be particularly easy to get merged, so I suggest you start there.

**Comment by ffaf1** [comment]
Tentative text for the second point:

> There is plenty of material to learn Haskell from! If you are new and want a thorough, practical introduction to the language, we suggest [CIS194](https://www.seas.upenn.edu/~cis194/fall16/). CIS194 is the introductory Haskell course for the University of Pennsylvania; it is free and will guide you from the basics to advanced features of the language.

**Comment by ffaf1** [comment]
Thanks!
