### ISSUE TITLE
Take down http://head.hackage.haskell.org/

### ISSUE THREAD

**Issue by nomeata** [haskell-infra/www.haskell.org#157]
In https://gitlab.haskell.org/ghc/head.hackage/-/issues/44#note_400996 Matthew Pickering says that http://head.hackage.haskell.org/ is obsolete and should be taken down (or maybe made a redirect to https://ghc.gitlab.haskell.org/head.hackage/)

**Comment by tomjaguarpaw** [comment]
Thanks for reporting that.

This repo is only for the `www` subdomain of `haskell.org` specifically. Anything else should be reported to the Haskell Infrastructure Admins. I suggest filing [an issue on their repo](https://github.com/haskell-infra/haskell-admins/issues/new) (although in practice I'm more likely to get a response if I also [contact them via IRC or email](https://github.com/haskell-infra/haskell-admins#the-team-and-how-to-contact-them). IRC seems to work best for that purpose.

**Comment by nomeata** [comment]
I’ll try https://github.com/haskell-infra/haskell-admins/issues/8 first; less intrusive.
