### ISSUE TITLE
First linux download link doesn't work / is confusing

### ISSUE THREAD

**Issue by ChrisJefferson** [haskell-infra/www.haskell.org#16]
The ppa Ubuntu section at the top of: https://www.haskell.org/downloads/linux/ says to do:

```
sudo add-apt-repository -y ppa:hvr/ghc
sudo apt-get update
sudo apt-get install -y cabal-install-XXX ghc-YYY
```

However, it was not obvious (to me) that I had to replace `XXX` and `YYY` with something else, and what that something else was.

Is there an option to always install the most recent version? Or could there are least be some text linking to another page with the currently released version number is, to tell us what to replace XXX and YYY with?

**Comment by ketzacoatl** [comment]
This is still an issue on the linux downloads page today. This issue should either be closed as "won't fix" or a solution proposed/defined.

**Comment by tomjaguarpaw** [comment]
Closing this as the downloads page doesn't mention these instructions anymore.

**Comment by ChrisJefferson** [comment]
Exactly the same text is still there, it's just moved to https://www.haskell.org/downloads/#package-manager

**Comment by tomjaguarpaw** [comment]
Oh, thanks, it's hidden under "Show linux distros".

**Comment by tomjaguarpaw** [comment]
I don't believe the PPA is being maintained anymore. Perhaps we should just remove this advice?

**Comment by ChrisJefferson** [comment]
I will admit I haven't tried it in a while (and don't want to, as my haskell works well right now and I'm afraid of breaking it :) )

**Comment by tomjaguarpaw** [comment]
Closing again, as the downloads page now really doesn't mention these instructions anymore.
