### ISSUE TITLE
Lingering references to Haskell Platform are confusing

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/www.haskell.org#164]
There are lingering references around the Haskell ecosystem to Haskell Platform, which is deprecated and mention of it removed from the site.  For example, [a user report](https://www.reddit.com/r/learnprogramming/comments/sgvk35/is_haskell_platform_no_longer_supported/).

Perhaps we can add back a `platform/` page which simply confirms that HP is deprecated and guides users to the downloads page.

(If we can also find old resources that mention the platform and ask them to update themselves then so much the better.)

**Comment by ulysses4ever** [comment]
One option is to add back the platform page but make it redirect immediately via the [meta refresh](https://en.m.wikipedia.org/wiki/Meta_refresh) method instead of trying to explain anything on it. I think that'd be more straightforward.

**Comment by tomjaguarpaw** [comment]
Unfortunately I don't think it's sufficient to *just* redirect the downloads page. Users will quite understandably confused about why all references to Haskell Platform on haskell.org just disappeared, despite claims in the books that they read that it is the official way to get Haskell. A simple note that Haskell Platform has been replaced by the method of the downloads page would suffice.

**Comment by tomjaguarpaw** [comment]
Closing this as it has been addressed by https://github.com/haskell-infra/www.haskell.org/pull/167, but we should collect a list of resources that mention Haskell Platform and ask them to update themselves.
