### ISSUE TITLE
Euterpea website links to www.haskell.org/platform

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/www.haskell.org#165]
https://www.euterpea.com/

This is particularly confusing because `www.haskell.org/platform` doesn't redirect to the downloads page (although with a trailing slash it does).

Mitigations

* Add back a platform page that links to download page (see https://github.com/haskell-infra/www.haskell.org/issues/164)
* Ask Euterpea website to update their instructions

**Comment by tomjaguarpaw** [comment]
Next action: Ask Euterpea website to update their instructions

**Comment by georgefst** [comment]
I mentioned this to the author in https://github.com/Euterpea/Euterpea2/pull/52, and references to the Haskell Platform do seem to have been fully removed from the website (alas, I think it's the only suggestion from that thread which was actually acted on).

**Comment by tomjaguarpaw** [comment]
Nice, thanks!
