### ISSUE TITLE
Should we link to LYAH open source fork?

### ISSUE THREAD

**Issue by ffaf1** [haskell-infra/www.haskell.org#174]
[This fork](https://learnyouahaskell.github.io/) of LYAH appeared on Discourse.

Should we link to it from the docs page? If I am reading correctly it seems a friendly fork and the fact that it is accepting patches means there will be less bitrot.

**Comment by tomjaguarpaw** [comment]
There's already a link to the original version. I don't see a compelling reason to switch yet and would prefer to see how the open source version develops. If it becomes significantly better than the original at some point, then we can switch.

**Comment by ffaf1** [comment]
Indeed the original version is alive and healthy.
