### ISSUE TITLE
HsColour

### ISSUE THREAD

**Issue by askeblad** [haskell-infra/www.haskell.org#186]
Perhaps the Haskell Organization would create a new repo for HsColour.

The hscolour Source repo URL returns a 404.

<hr>

the files in the following repo could be downloaded and copied to a new `github.com/haskell/hscolour` repo

https://github.com/vaerksted/HsColour

warning: [-Wtabs]
modified to replace tabs with spaces

warning: [-Wmissing-home-modules]
modified to add an Other-Modules field

warning: [-Wmissing-methods]
ANSI.hs (unmodified)

```
Language/Haskell/HsColour/ANSI.hs:62:10: warning: [-Wmissing-methods]
    * No explicit implementation for
        `toEnum'
    * In the instance declaration for `Enum Highlight'
   |
62 | instance Enum Highlight where
   |
```

**Comment by askeblad** [comment]
@malcolmwallace
@bringert

ping

**Comment by tomjaguarpaw** [comment]
(On the one hand, this doesn't really belong here since it relates to https://github.com/haskell, a completely different "GitHub organization". On the other hand I don't think there is a way to raise an issue on the organization itself; you can only raise issues on individual repositories. Until such a facility exists (or someone creates a "meta" repo in the haskell organization, perhaps it's best to host this discussion here.)

**Comment by askeblad** [comment]
appears to be orphanware yet HsColour when building GHC is searched for

any volunteer to modify the code to deal with the outstanding warning [-Wmissing-methods]

**Comment by gbaz** [comment]
hscolour lives here for now afaik https://github.com/hackage-trustees/malcolm-wallace-universe

**Comment by askeblad** [comment]
>  issue on the organization

a `github.com/haskell/haskell.github.io` repo could direct users to an **Issues** page, but, would there be that many organization issues, or unattended to Issues/PRs in organization repos, which could be cited and/or linked to in opened organization issues, to warrant creation of such a "meta" repo

https://github.com/haskell-infra/www.haskell.org/issues/181 original idea for such a repo

**Comment by askeblad** [comment]
a `github.com/haskell/pasture` repo might also be created where the  
sub-directories would be relocated abandoned Haskell Organization repos

**Comment by tomjaguarpaw** [comment]
> hscolour lives here for now afaik https://github.com/hackage-trustees/malcolm-wallace-universe

It seems this issue is resolved.

Now that https://github.com/haskell/meta exists I suggest that questions about https://github.com/haskell/ are raised there.

**Comment by askeblad** [comment]
@tomjaguarpaw

https://github.com/haskell/meta/pull/2

based on GH Linguist adds to meta/README.md a list of Organization repos
