### ISSUE TITLE
How should we advertise Stack installation on FreeBSD?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/www.haskell.org#190]
Regarding the [Downloads page](https://www.haskell.org/downloads/):

It turns out that Stack does support FreeBSD after all. See <https://github.com/commercialhaskell/stack/issues/5674#issuecomment-1086786046=>. However, its installation method differs from Windows, MacOS and Linux. For those we can just link to [the Stack install guide](https://docs.haskellstack.org/en/stable/install_and_upgrade/). How should we advertise Stack installation on FreeBSD? Perhaps we could say

> To install stack, follow the instructions [here](https://docs.haskellstack.org/en/stable/install_and_upgrade/) (unless you are on FreeBSD, in which case run `pkg install hs-stack`).

Does anyone have a strong opinion on this?

**Comment by hasufell** [comment]
This will revert the efforts I made in the previous PRs to **unify installation methods** and give users simple and *concise* instructions.

Further, FreeBSD is not a "primary" platform in terms of GHC support. That means there sometimes are GHC releases without FreeBSD bindists. It will not block the release. So I don't see a justification to complicated the instructions, while [this PR](https://github.com/haskell-infra/www.haskell.org/pull/188) already shows detailed information about FreeBSD ports packages.

**Comment by tomjaguarpaw** [comment]
Well, we can't say "Stack does not support FreeBSD" when it does. If we move to #188 or something similar then I suppose we could say

> To install stack, follow the instructions [here](https://docs.haskellstack.org/en/stable/install_and_upgrade/) (for FreeBSD see below).

**Comment by hasufell** [comment]
We just remove any note about FreeBSD. If someone picks the first method (ghcup) they will likely install stack through that (because we ask them interactively). If they happen to follow the stack link, they will be disappointed and probably create a bug report on stack issue tracker (good). If they install from ports, everything works.

**Comment by hasufell** [comment]
Also note: the stack script doesn't support darwin M1 either. We also don't have a specialized note about that.

**Comment by tonyday567** [comment]
We should detect if the user is on FreeBSD (or darwin M1 etc), and provide a specific message and thus avoid the conditional OS clutter.

**Comment by hasufell** [comment]
> We should detect if the user is on FreeBSD (or darwin M1 etc), and provide a specific message and thus avoid the conditional OS clutter.

Well, the idea of the download page was to provide an installation method that works across all platforms, so we can avoid this conditionality.

**Comment by tonyday567** [comment]
I have no experience of the Haskell platform page, so I'm not sure if the comparison is a bad thing; I imagine it was horrible from your usage.

I would instead refer to the rust install page: https://www.rust-lang.org/tools/install. It doesn't seem to be interactive. I like how it hides the detail of specific OSes where it doesn't apply.

**Comment by hasufell** [comment]
> I have no experience of the Haskell platform page, so I'm not sure if the comparison is a bad thing; I imagine it was horrible from your usage.
> 
> I would instead refer to the rust install page: https://www.rust-lang.org/tools/install. It doesn't seem to be interactive. I like how it hides the detail of specific OSes where it doesn't apply.
> 
>  

Yeah. We have that already: https://www.haskell.org/ghcup/

**Comment by jneira** [comment]
Agree with @hasufell, i would remove the freebsd note and continue pointing to https://docs.haskellstack.org/en/stable/install_and_upgrade/, that page should contain specific instructions for freebsd, and it would be a good thing for stack docs and for keeping clean the download page, imho

**Comment by tomjaguarpaw** [comment]
Yes, I can see the value of that approach. It takes the point of view that it's the responsibility of the Stack install guide to list the methods of installation on all the platforms they support, not the www.haskell.org website.

**Comment by tomjaguarpaw** [comment]
OK, in https://github.com/haskell-infra/www.haskell.org/pull/194 we made no specific mention of Stack support on FreeBSD.
