### ISSUE TITLE
Update ghc downloads/ latest symlink to 8.10.1

### ISSUE THREAD

**Issue by bezirg** [haskell-infra/www.haskell.org#20]
Currently, the latest downloads (and docs) point to 8.8.3:

https://downloads.haskell.org/~ghc/latest/

Please update it to point to 8.10.1

```
ln -s https://downloads.haskell.org/ghc/8.10.1/  https://downloads.haskell.org/~ghc/latest/
```

**Comment by gwils** [comment]
I believe @bgamari  is responsible for this

**Comment by delirehberi** [comment]
it seems updated. you can close the issue @gwils

**Comment by bezirg** [comment]
Shouldn't it now point to 8.10.2?

**Comment by bezirg** [comment]
Something is off, the `latest` directory contains the **8.10.1** binaries/sources,  while the `latest/docs` directory contains the expected 8.10.2 docs

**Comment by bgamari** [comment]
It looks fine from my end. I can only imagine that the silly CDN is now confused. I've tried purging. Try again?

**Comment by delirehberi** [comment]
I think its ok now.

![image](https://user-images.githubusercontent.com/803964/97327817-6ab71600-1886-11eb-9f74-792a9e0bd7d3.png)
