### ISSUE TITLE
Add a "Start Coding" section. 

### ISSUE THREAD

**Issue by lsmor** [haskell-infra/www.haskell.org#207]
Hi. It isn't a secret that newcommers have problems setting up a Development environment. The reason is that there is no single place within haskell.org, `hls` documentation nor `ghcup` documentation where you can find a **minimal, clear and strightforward guide** (MCSG from now on). 

Just to be clear and avoid unproductive discussion. Let me explain what a MCSG is:

- Because is a **guide** it should guide you step by step from _"My computer only has OS software installed"_ to _"I am programming in Haskell with the full power of an IDE"_
- Because is **strightforward** it should not branch. _you don't want to use `vscode`?_ ok, let me point you to "other editors" link, but such a link shouldn't be part of the guide itself.
- Because is **clear** each step should not be larger than one click or one execution command. 
- Because is **minimal** it should not give more information than necessary. If I have to navegate across multiple markdown hearders to find out how to configure the editor, or how to install the building tool, then it isn't minimal.

Some consequences of having a MCSG is that you need to select sensible defaults hence being biased towards tooling. In the Haskell case, the alternative which has proved better consistency is `ghcup` + `ghc` + `cabal` + `hls` + `vscode`. This isn't an opinion. `hls` is biased towards `vscode` and `stack` does not integrate well with `hls` unless you configure it properly (using `system-ghc`). 

If we were about to choose other editors or `stack` as default options, then we would need to provide extra configuration instructions for them, hence It wouldn't be **minimal**. If we were about to let the user decide between `stack` and `cabal` or `vim`/`emacs`/`vscode` then It wouldn't be **straightforward**. Lastly, if we don't use `ghcup` it would be **clear** because downloading each tool manually and configuring each of them to work properly and not break on updates is difficult if you aren't an experienced user.

The benefits of having a MCSG are clear. Many developers (In my experience, much more than I would have expect) do not know what a language server is, do not know or care about unix philosophy, do not want to read documentation, do not actually read documentation if they can copy paste a command in the terminal. If these developers come to haskell.org and find different ways of installing haskell, not mention about editors, many different tools, etc... the most probable outcome is "I will just installed pycharm and be happy". Actually, this is what I found helping newcommers (objectively, not a huge sample: a few people over cardano's discord and five co-workers). 

In [Discourse](https://discourse.haskell.org/t/get-a-haskell-development-environment-in-three-steps/4822) I posted a link to a [github gist](https://gist.github.com/lsmor/bb632565cd96be9da589b6e91f80f9ba) having a three step guide which is commited to MCSG as defined here. Whether it should be on `hls` home page or haskell.org is debatable, that's why I am opening this issue. If you consider this belongs to `hls` just tell me. In my opinion, haskell.org should provide this information, because is very unlikely that newcommers now what a language server is, hence there is low probability of them searching for `haskell language server` instead of just `haskell`.  

The guide ifself is only the first markdown header. There are two more sections including 

- "other editor" pointing to  `hls` documentation
-  Instructions for `stack` integration, because it is still a widely used tool. 

by the way, `stack` instructions are a little bit verbose because there is a surprisingly high amount of `stack` user who don't know how `stack` works. Every now and then there is a question in SO asking "[why](https://stackoverflow.com/questions/70267593/on-a-stacks-package-file-what-is-the-difference-between-library-and-executable/70272743#70272743) [stack](https://stackoverflow.com/questions/69374974/transformers-0-5-6-2-from-stack-configuration-does-not-match-0-3-0-2/69379846#69379846) [doesn't](https://stackoverflow.com/questions/62762252/installing-aeson-package-using-stack/62792161#62792161) [build](https://stackoverflow.com/questions/61673967/stack-build-error-while-building-package-aeson-cabal-exitfailure-1/61751248#61751248) [my project](https://stackoverflow.com/questions/72850322/how-does-the-workflow-with-haskell-stack-work/72855353#72855353)"

**Comment by tomjaguarpaw** [comment]
For reference, a couple of related issues:

* https://github.com/haskell-infra/www.haskell.org/issues/189
* https://github.com/haskell-infra/www.haskell.org/issues/136

**Comment by rebeccaskinner** [comment]
I’d love to see a PR for this. I do expect that it might take a while to land because there will probably be a lot of input from the community, but I do feel like this is really high value.
