### ISSUE TITLE
Downloads page needs quick explainer

### ISSUE THREAD

**Issue by AMDphreak** [haskell-infra/www.haskell.org#21]
Hi,

I'm a little new here but looked into Haskell before and was annoyed by all the options that are presented without [sufficient] explanation on the downloads page.

Instead of this:

> There are three widely used ways to install the Haskell toolchain on supported platforms. These are:
> 
> Minimal installers: Just GHC (the compiler), and build tools (primarily Cabal and Stack) are installed globally on your system, using your system’s package manager.
> 
> Stack: Installs the stack command globally: a project-centric build tool to automatically download and manage Haskell dependencies on a project-by-project basis.
> 
> Haskell Platform: Installs GHC, Cabal, and some other tools, along with a starter set of libraries in a global location on your system.

Please write a short introduction about general programmer workflow, and describe the basic problem that each tool is supposed to solve. Every tool/problem arises as a result of observing a problem and conceptualizing a tool/feature to improve the basic model of programming, which is 1. write 2. compile 3. run 4. debug 5. distribute 6. manage updates (dependencies).

The idea of what is "minimal" in an installer is highly subjective and completely meaningless to someone who is unfamiliar with the tools, since their conception of what is necessary for programming is different from the developer's. You can define "minimal installer" later after the user is familiar with the general ideas behind the tools.

General guidelines: use "if/then" statements to describe when a user must make a selection/decision about what to pay attention to.

At one point I had read and understood the comparison of these tools but like most people, I use this information and then discard it after I've made my decision, unless I discover an exception to my expectations about what kind of workflow I am getting from the set of tools I have chosen to investigate.

Please reply and help me help you make this page more accessible to new people.

**Comment by mattbaumann** [comment]
> The idea of what is "minimal" in an installer is highly subjective and completely meaningless to someone who is unfamiliar with the tools, 

Yes, I definitely agree with you on this one. But I also think, the writer of the download page, just was to ambitious and over thought the thing. The download page should be for beginners, not experts they already know the tools. Therefore, simply provide a link to a complete installer with all tools is sufficient.

And yes, your absolutely right, for experts there should be a link to a page with an "if-else" map to find the tool necessary. Yet, many items on the download page are unnecessary, since they are today the same tool and installer.

**Comment by emilypi** [comment]
Hi @AMDphreak - we appreciate the feedback. 

>... and describe the basic problem that each tool is supposed to solve.

If you click on "minimal installer", "cabal" ,or "stack", it takes you to a link that gives you a description of what problems each tool solves. 

>  Please write a short introduction about general programmer workflow,

> Every tool/problem arises as a result of observing a problem and conceptualizing a tool/feature to improve the basic model of programming, which is 1. write 2. compile 3. run 4. debug 5. distribute 6. manage updates (dependencies).

I disagree that the downloads page is the correct place to include an introduction to workflow, as it is a place for blessed downloadables, not to teach you how to use a particular workflow. That is the purview of documentation, which, if you click on the link, takes you to tutorials that cover the subject matter. It's worth noting that other languages follow this pattern. You'll find similar structure with Pythong or Rust's websites. 

> The idea of what is "minimal" in an installer is highly subjective and completely meaningless to someone who is unfamiliar with the tools,

"Minimal installer" (or Minimal Install) is common vernacular used for nearly every linux distribution, and it is similarly used here. It means "barebones library + package managers". I'm surprised that this is considered meaningless!  

Either way, if you want to expand and rework this page, you can always submit a PR with what you think is more appropriate, and then we can debate concretions. I'm happy to consider rewrites and edits, so feel free to open up the discussion!

**Comment by AMDphreak** [comment]
> Hi @AMDphreak - we appreciate the feedback.
> 
> > ... and describe the basic problem that each tool is supposed to solve.
> 
> If you click on "minimal installer", "cabal" ,or "stack", it takes you to a link that gives you a description of what problems each tool solves.
> 
> > Please write a short introduction about general programmer workflow,
> 
> > Every tool/problem arises as a result of observing a problem and conceptualizing a tool/feature to improve the basic model of programming, which is 1. write 2. compile 3. run 4. debug 5. distribute 6. manage updates (dependencies).
> 
> I disagree that the downloads page is the correct place to include an introduction to workflow, as it is a place for blessed downloadables, not to teach you how to use a particular workflow. That is the purview of documentation, which, if you click on the link, takes you to tutorials that cover the subject matter. It's worth noting that other languages follow this pattern. You'll find similar structure with Python or Rust's websites.
> 
> > The idea of what is "minimal" in an installer is highly subjective and completely meaningless to someone who is unfamiliar with the tools,
> 
> "Minimal installer" (or Minimal Install) is common vernacular used for lots of OSS (see: nearly every linux distribution), and it is similarly used here. It means "barebones library + package managers". I'm surprised that this is considered meaningless!
> 
> Either way, if you want to expand and rework this page, you can always submit a PR with what you think is more appropriate, and then we can debate concretions. I'm happy to consider rewrites and edits, so feel free to open up the discussion!

Thanks. To be completely honest, I may not get to do that any time soon. I will keep it in mind for later.

**Comment by ketzacoatl** [comment]
Should this be closed as "won't fix", or are there next steps we can take?

**Comment by emilypi** [comment]
@ketzacoatl there's not much to do if @AMDphreak or others don't want to address this. It's been a year. I say close for now.
