### ISSUE TITLE
Introductory and intermediate book is the same

### ISSUE THREAD

**Issue by avanegas-carecloud** [haskell-infra/www.haskell.org#218]
Hello, I noticed in the documentation page, one of the introductory books is listed as "Beginning Haskell" and one of the intermediate books is listed as "Practical Haskell". While not obvious, these books are the same, with Practical Haskell being the second (and now, third) edition of Beginning Haskell. Normally, this would get changed via a simple pull request except I don't know enough about the books to determine if they belong in the introductory or intermediate section exclusively.

**Comment by TikhonJelvis** [comment]
Thanks for noticing that. I haven't read the book myself, but looking at the table of contents, I'd lean towards keeping it in the intermediate section. Looks like the book starts from the basics and doesn't require Haskell/FP background knowledge, but quickly gets into intermediate topics like Conduit, databases and DSL design.

How about waiting for a few days in case somebody has a clearer idea and then, if nobody else has commented on the issue, opening a PR?
