### ISSUE TITLE
Link for Haskell Art is dead

### ISSUE THREAD

**Issue by advalt** [haskell-infra/www.haskell.org#229]
on this page https://www.haskell.org/community/
this link https://lurk.org/groups/haskell-art/

**Comment by TikhonJelvis** [comment]
Thanks! I can open a PR to remove the dead link.

Do you know if there's a new page for the same group? No worries either way—if there's a new link, we can always add that as a separate PR.

**Comment by tomjaguarpaw** [comment]
Fixed by https://github.com/haskell-infra/www.haskell.org/pull/230
