### ISSUE TITLE
Fix horizontal scrolling / width on mobile

### ISSUE THREAD

**Issue by andys8** [haskell-infra/www.haskell.org#246]
The video shows that the start page haskell.org behaves glitchy on mobile. You can scroll horizontally, but you shouldn't be able to. This doesn't result in a terrible user experience, but still is an issue that should be avoided.

https://user-images.githubusercontent.com/13085980/216581498-71a48d5f-7a4d-478f-8a8f-8b674b9851aa.mp4

I tested with Android 13 and latest Chrome and Kiwi Browser on a OnePlus 8.

**Comment by andys8** [comment]
It's noteworthy that there is open PR for improvements of the landing page. There is a chance this PR would also solve the mentioned issue, but it has to be tested to know if this is the case or not.

https://github.com/haskell-infra/www.haskell.org/pull/242

**Comment by tomjaguarpaw** [comment]
Interesting, thanks. I'll investigate that fix.

**Comment by tomjaguarpaw** [comment]
As far as i can tell #242 seems to make things worse! I think the cause is the `>>` on the right hand side of the Testimonials scroller.

**Comment by tomjaguarpaw** [comment]
Yeah, #242 does make things worse, because it forces the "Haskell logo, Haskell, An advanced, purely functional programming language" block to be on the same horizontal level as "Declarative, statically typed code, primes code, Get Started" block, making the screen wider. The status quo is that on narrow screens the first block appears above the second.

**Comment by andys8** [comment]
How would you suggest dealing with this issue? Fixing the current version independently of #242 and making sure that #242 only gets merged if it doesn't make it worse / break it again? Or work on #242 directly?

**Comment by tomjaguarpaw** [comment]
This issue seems to be independent of #242 so I suggest just finding a fix that addresses the reason that the `>>` falls off the screen.

**Comment by andys8** [comment]
I wanted to start taking a look, but `buildAndWatch` ended up in:

```
/nix/store/2md452mq5labdcxlsc5gfik97dhxabbr-haskell-org-0.1.0.0
Removing _site...
Removing _cache...
Removing _cache/tmp...
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  updated 2015-11-10-Haskell-Org-Board-Resolution.pdf
  [ERROR] _cache/a98f5fd1dec8ada591e76ae4112817f9 for Hakyll.Core.Resource.Provider.MetadataCache/community.markdown/body: Store.set: invalid argument (invalid byte sequence)
```

Is there a quick fix, or is this a reason to open an issue?

**Comment by TikhonJelvis** [comment]
@andys8 That looks related to #29 :/. Could you try explicitly setting the locale before running the script?

```
LC_ALL=C.UTF-8 ./buildAndWatch
```

I though that #236 should have fixed that, but apparently not. I'll need to take another look into why this is a problem and how we can fix it more robustly.
