### ISSUE TITLE
buildAndWatch fails because of locale / invalid byte sequence

### ISSUE THREAD

**Issue by andys8** [haskell-infra/www.haskell.org#249]
## Issue

```shell
/nix/store/2md452mq5labdcxlsc5gfik97dhxabbr-haskell-org-0.1.0.0
Removing _site...
Removing _cache...
Removing _cache/tmp...
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  updated 2015-11-10-Haskell-Org-Board-Resolution.pdf
  [ERROR] _cache/a98f5fd1dec8ada591e76ae4112817f9 for Hakyll.Core.Resource.Provider.MetadataCache/community.markdown/body: Store.set: invalid argument (invalid byte sequence)
```

## Related

* People pointing out the error is related to UTF8 encoding and hakyll:
https://github.com/jaspervdj/hakyll/issues/614
* Similar issue in nixpgks: https://github.com/NixOS/nixpkgs/pull/122117#discussion_r1058479008
* #29
* #236 
* https://github.com/haskell-infra/www.haskell.org/issues/246#issuecomment-1415836754

## System

I'm using OS: Manjaro 22.0.0 Sikaris, arch based.
Nix 2.8.1 installed as package manager, but not OS.

https://wiki.archlinux.org/title/locale

## Locale

```shell
$ locale -a
C
C.UTF-8
de_DE.utf8
en_DE.utf8
en_US.utf8
POSIX

$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

**Comment by TikhonJelvis** [comment]
Thanks for the detailed error report! I'll take a look at this. Frankly, I've had too many headaches from locale settings with Haskell + Nix—on another project I ended up rewriting my Haskell code to always use UTF-8 regardless of the locale settings, so I'll try that here too. Not sure whether the same approach will work with Hakyll though.

**Comment by andys8** [comment]
Sounds reasonable.

I think as long as there is this line (and maybe the others), passing an environment value from the outside is not possible as workaround.

https://github.com/haskell-infra/www.haskell.org/blob/0a374ccf210e1880b9020151b02d7d2f8a0ae876/buildAndWatch#L15
