### ISSUE TITLE
Haskell example on landing page cut off on mobile

### ISSUE THREAD

**Issue by andys8** [haskell-infra/www.haskell.org#251]
The example is not fully visible on my device (6.6 inch screen, but experience depending int he device).

I tried around, and 4 spaces are an improvement, but actually 2 spaces might be necessary with the current setup.

Are you open to using less than 6 spaces of indentation in the code?

![Screenshot_2023-02-03-14-45-16-70_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/13085980/216618939-39479e05-d2c4-43d9-8ff5-051dad4ae925.jpg)

https://user-images.githubusercontent.com/13085980/216618966-7c9b8985-83c7-42a1-b3db-24992d4999e1.mp4

**Comment by tomjaguarpaw** [comment]
> Are you open to using less than 6 spaces of indentation in the code?

Yeah absolutely. A PR to change to 2 spaces would be a good first step.

**Comment by andys8** [comment]
The original example is:

```haskell
primes = filterPrime [2..]
      where filterPrime (p:xs) =
              p : filterPrime [x | x <- xs, x `mod` p /= 0]
```

The use of the `where` keyword constrains indentation a bit. One of these? Or do you have a different suggestion?

```haskell
primes = filterPrime [2..]
  where
    filterPrime (p:xs) =
        p : filterPrime [x | x <- xs, x `mod` p /= 0]
```

```haskell
primes = filterPrime [2 ..] where
  filterPrime (p : xs) =
    p : filterPrime [x | x <- xs, x `mod` p /= 0]
```

**Comment by tomjaguarpaw** [comment]
The last one seems fine and is most likely to fit.

(There's also talk of replacing the example with something more practical, but I don't think that should affect what we choose to do about spacing for now.)

**Comment by ulysses4ever** [comment]
@andys8 `where` doesn't require more indentation after it, so this is legit too:

```
primes = filterPrime [2..]
  where
  filterPrime (p:xs) =
    p : filterPrime [x | x <- xs, x `mod` p /= 0]
```
But leaving it on the first line probably makes more sense.

**Comment by andys8** [comment]
Solved via https://github.com/haskell-infra/www.haskell.org/pull/254
