### ISSUE TITLE
Haskell "try it" not working on Android

### ISSUE THREAD

**Issue by andys8** [haskell-infra/www.haskell.org#252]
There is a prompt that lets you try Haskell on the landing page. Input doesn't seem to work on Android in mobile browsers. I tested on 2 devices (Samsung and OnePlus) with 2 different browsers (Kiwi and Chrome). On the other hand it *is* working on iOS (Chrome and Safari).

https://user-images.githubusercontent.com/13085980/216621119-2bc84307-c5ed-4d95-8a9a-6aeea22605ec.mp4

**Comment by andys8** [comment]
The underlying implementation is https://github.com/chrisdone/jquery-console. The project isn't maintained and there are no newer versions available.

But luckily there are 2 open pull requests suggesting a solution to the Android issue.

* https://github.com/chrisdone/jquery-console/pull/71
* https://github.com/chrisdone/jquery-console/pull/68

So, a fix seems to be possible. The alternative would be to hide "try it" on Android.

**Comment by tomjaguarpaw** [comment]
FWIW the "try it" app is very limited and there have been suggestions to replace it with a proper [Play Haskell](https://play-haskell.tomsmeding.com/).

**Comment by tomjaguarpaw** [comment]
See https://github.com/haskell-infra/www.haskell.org/issues/185

**Comment by tomjaguarpaw** [comment]
You can give it a go if you like!
