### ISSUE TITLE
Cachix action is failing

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/www.haskell.org#266]
See, for example https://github.com/haskell-infra/www.haskell.org/actions/runs/4845420159/jobs/8634334648#step:4:13

I thought that https://github.com/haskell-infra/www.haskell.org/pull/265 might fix it, but it does not: https://github.com/haskell-infra/www.haskell.org/actions/runs/4845428718/jobs/8634343440?pr=265

@TikhonJelvis or @rebeccaskinner, as the Nix experts, would you mind taking a look?

**Comment by TikhonJelvis** [comment]
Looks like this is due to https://github.com/cachix/cachix-action/issues/144

The fix is to update `cachix/install-nix-action` to v20. May as well do that alongside #265.
