### ISSUE TITLE
Security page on www.haskell.org

### ISSUE THREAD

**Issue by frasertweedale** [haskell-infra/www.haskell.org#293]
Hello maintainers,

This issue is mainly a heads-up and Request For Comment, before we do the work.
Please give your feedback!

---

The Security Response Team would like a web presence on www.haskell.org.  It is where
we would publish:

- The team members and how to contact the team
  - Team members and bios: https://discourse.haskell.org/t/haskell-security-response-team-announcement-and-q2-2023-report/6931#srt-membership-and-kick-off-2
- How to report security advisories
  -  A starting point for the content: https://discourse.haskell.org/t/haskell-security-response-team-announcement-and-q2-2023-report/6931#database-is-open-for-submissions-6
- Security guides for Haskell project maintainers (e.g. CI best practices, release management practices)
  - source for our guides is in our repo: https://github.com/haskell/security-advisories/tree/main/guides
  - suggest separate pages for each guide, and a section on the main security page that lists them.
- SRT quarterly 
  - reports are in our repo: https://github.com/haskell/security-advisories/tree/main/reports
  -  suggest separate pages for each guide, and a **section** on the main security page that lists them.
- Table of Contents for the security page.

To make the resource discoverable, we would also like a link on the landing page,
perhaps a new "Security" node in this nav bar: 
![Screenshot from 2024-05-03 10-51-29](https://github.com/haskell-infra/www.haskell.org/assets/2331938/98e6ab79-b76f-47d2-9b3b-02ae36661ede)

But, if the maintainers have different ideas, please share.

**Comment by frasertweedale** [comment]
Andre Esapze is working on this at ZuriHac. Thank you Andre!

**Comment by aespaze42** [comment]
I have push the commit [there](https://github.com/aespaze42/www.haskell.org/commit/bf6edbf1a8c9c54bc83c8d3d10882e1d1ffdab8e). Thank you very much for your warm welcome.
