### ISSUE TITLE
wiki[.]haskell[.]org responds with a 502 bad gateway error

### ISSUE THREAD

**Issue by zennad** [haskell-infra/www.haskell.org#318]
'wiki.haskell.org', which is referenced at the bottom of the homepage and on the documentation page, returns a 502 bad gateway response.

I realise that the source of the wiki is not managed in this repo, nor does the wiki appear to be hosted by the same server as the main site. However, I thought that it might be worth having a ticket to track this issue

**Comment by cotrone** [comment]
It's being worked on, chreekat posted that there was an unsuccessful system upgrade on discourse https://discourse.haskell.org/t/wiki-haskell-org-is-down/10664

**Comment by gbaz** [comment]
In the future, you can report issues on irc, emailing admin at haskell dot org rather than here, and follow the status tracker at http://status.haskell.org (though it is only manually updated).
