### ISSUE TITLE
can't enter variables or functions on main page prompt

### ISSUE THREAD

**Issue by jszabo98** [haskell-infra/www.haskell.org#37]
x = 1
<hint>:1:3: parse error on input ‘=’

double x = x * 2
<hint>:1:10: parse error on input ‘=’

**Comment by gbaz** [comment]
yes, you can't enter definitions. its a stateless repl.

**Comment by jszabo98** [comment]
One of the reasons learning Haskell in the beginning becomes frustrating.

**Comment by TikhonJelvis** [comment]
GHCi lets you specify definitions like `x = 1`, so it seems like a reasonable thing to expect. I'm not sure how easy it would be to add to the REPL on the website though.

**Comment by gbaz** [comment]
you'd need to patch the tryhaskell codebase, which is the backend. also, it would require making the repl stateful. i think its absolutely not worth it to try to change the whole architecture for whats supposed to be a small interactive tutorial.
