### ISSUE TITLE
inappropriate use of url

### ISSUE THREAD

**Issue by apparluk** [haskell-infra/www.haskell.org#43]
![discourse](https://user-images.githubusercontent.com/52227507/97499858-e7252400-196e-11eb-8063-aacaec5b6876.png)

**Comment by TikhonJelvis** [comment]
I'm sorry, what's the inappropriate use of the URL here?

**Comment by apparluk** [comment]
Whom 'us' refers to in the screenshot is unspecified.

Haskell.org neither specifies Committee liability nor with the conclusion of terms where liability rests.

Consult with counsel.
