### ISSUE TITLE
Where is the source of the cabal subtree?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/www.haskell.org#47]
I'm confused because nothing below https://www.haskell.org/cabal/ seems to be in the repository. I just filed two tickets [[1]](https://github.com/haskell-infra/www.haskell.org/issues/45) [[2]](https://github.com/haskell-infra/www.haskell.org/issues/46) about that subtree, but maybe this is the wrong place for them. Am I looking for the source in the wrong place? If I want to make a change to that subtree where should I do so?

**Comment by fgaz** [comment]
https://github.com/haskell/cabal-website

**Comment by tomjaguarpaw** [comment]
Thank you!
