### ISSUE TITLE
IO actions not working in sandbox

### ISSUE THREAD

**Issue by 3Rafal** [haskell-infra/www.haskell.org#55]
When running suggested example 
```haskell
do line <- getLine; putStrLn line
```
in sandbox I get an error as below
![image](https://user-images.githubusercontent.com/22241847/103385050-2e5b9c80-4af9-11eb-89a9-8824afc3b1b8.png)

This behavior seems to be common for all IO actions.

**Comment by gbaz** [comment]
Looks like the backend changed to not support them. The site should probably be updated accordingly (to not suggest 'em)
