### ISSUE TITLE
footer needs an update

### ISSUE THREAD

**Issue by idabzo** [haskell-infra/www.haskell.org#57]
It’s 2021 already, and the webpage shows the wrong year in the footer - I assume, that problem should disappear after the build. It’s a small task, but very important - it will bring the present and the future to haskell.org :D could someone do that?

**Comment by TikhonJelvis** [comment]
Thanks for noticing that :).

Should be updated next time the site is rebuilt and deployed, which should happen in the next couple of days.

**Comment by TikhonJelvis** [comment]
The footer is up to date now :).
