### ISSUE TITLE
Committee Membership out of date?

### ISSUE THREAD

**Issue by tbm** [haskell-infra/www.haskell.org#62]
https://www.haskell.org/haskell-org-committee/ says

> Ryan Trinkle (term ends 2020)
> Tikhon Jelvis (term ends 2020)
> George Wilson (term ends 2020)

Should the page be updated?

**Comment by TikhonJelvis** [comment]
We're a bit behind schedule on voting for new members. We'll have a vote and discussion this week and announce new members (as well as updating the page) either later this week or early next week.

**Comment by TikhonJelvis** [comment]
New members were announced recently. We'll update the site first, alongside the changes in #64.

Thanks for spotting this originally, by the way :). It's easy for little bit of the site to get out of date without reminders like this.
