### ISSUE TITLE
amazon smile link in the donations page broken

### ISSUE THREAD

**Issue by vu3rdd** [haskell-infra/www.haskell.org#68]
The amazon smile link on the [donations page](https://www.haskell.org/donations/) has not been populated with the [right link](https://smile.amazon.com/). Perhaps a little text explaining how to use that service and find haskell.org as a charity can help as well.

**Comment by TikhonJelvis** [comment]
Thanks for spotting this. Just submitted a PR with a quick fix.

**Comment by ketzacoatl** [comment]
@TikhonJelvis if that's been merged, is it good to close out this issue, or is there another task?
