### ISSUE TITLE
Add book "Haskell from the Very Beginning"

### ISSUE THREAD

**Issue by johnwhitington** [haskell-infra/www.haskell.org#7]
(I'd do a PR myself, but as the author, it would be a bit presumptuous for me to choose where in the list to put it!)

The page is https://www.haskell.org/documentation/

The book title is "Haskell from the Very Beginining"

The URL is https://haskellfromtheverybeginning.com/

**Comment by ketzacoatl** [comment]
With that PR merged, this issue should be closed, no?
