### ISSUE TITLE
Should link to platform repo have been removed?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/www.haskell.org#77]
The README used to have a link to the [platform repository](https://github.com/haskell/haskell-platform/tree/master/website) but it was removed in

https://github.com/haskell-infra/www.haskell.org/commit/9dcf082b4578c3b09211ea74c10485bca0f6b2d2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L11

Was the removal intentional? It's not clear to me from the rest of the commit why this part should have been removed. @hasufell can you remember? Perhaps it was unintentional?

**Comment by hasufell** [comment]
Yes, it is removed, because haskell platform has been removed from the downloads page as discussed in the related tickets.

https://github.com/haskell-infra/www.haskell.org/issues/12
https://github.com/haskell-infra/www.haskell.org/pull/71

**Comment by tomjaguarpaw** [comment]
But that section is supposed to describe what subsites are present under https://www.haskell.org/ and doesn't have anything to do with whether the download page links to the platform. Indeed https://www.haskell.org/platform/ still exists on the website so I think that the link to the platform repository should remain where it was.

**Comment by hasufell** [comment]
Ah I see. Seems legit.
