### ISSUE TITLE
Set up automated deployment from CI

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/www.haskell.org#83]
Davean explained to me how we can automate deployments from CI by via sftp. The process is

* store an SSH private key as [a secret in the CI system](https://docs.github.com/en/actions/reference/encrypted-secrets)
* send the public key to `admin@haskell.org` for the admins to install on the server
* each CI build of master, `sftp` the site artifact directly to the `www.haskell.org` server

cc @TikhonJelvis 

Related to https://github.com/haskell-infra/www.haskell.org/issues/66

**Comment by tomjaguarpaw** [comment]
First step would be to build the artifact. This is ready as https://github.com/haskell-infra/www.haskell.org/pull/82.

**Comment by ketzacoatl** [comment]
This is exciting! While I believe a simpler setup with static hosting would be better suited to the situation, I am glad to see CI improving!
