### ISSUE TITLE
Wrong link at www.haskell.org/ghc

### ISSUE THREAD

**Issue by visortelle** [haskell-infra/www.haskell.org#92]
Didn't find a better place to report.

Page: https://www.haskell.org/ghc/distribution_packages.html#macosx

Replace Homebrew link from http://www.homebrew.org/ to https://brew.sh/

**Comment by tomjaguarpaw** [comment]
Thanks for reporting this issue. I believe that the source for this page is maintained at https://gitlab.haskell.org/. When I get some time I will try to find a more precise location for you.

**Comment by ulysses4ever** [comment]
It's

https://gitlab.haskell.org/ghc/homepage/-/blob/master/distribution_packages.mkd

Pretty sure a PR would be welcome. Do you want to do it?

**Comment by visortelle** [comment]
I'll create a PR.

**Comment by visortelle** [comment]
Created a PR in the right place https://gitlab.haskell.org/ghc/homepage/-/merge_requests/77

Closing.
