### ISSUE TITLE
theTUNDRA community link 404

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/www.haskell.org#98]
https://www.haskell.org/community/ contains a link to theTUNDRA which returns 404

1. Fix it
2. Why didn't link checker find it?

@TikhonJelvis any ideas about 2?

**Comment by TikhonJelvis** [comment]
Looks like the site gives a 200 response, at least to a basic `curl` command. Looks like they return a 200 with an HTML page that just links in some JavaScript, and the JavaScript presumably figures out the actual content and displays a 404 message. (Isn't the modern web grand?)

I don't see any general way for linkchecker to catch issues like this, short of a headless browser and some heuristics or machine learning for guessing when a page isn't "valid" any more.

I'm on a Windows laptop so I checked this with [some online curl tool](https://reqbin.com/curl):

```
curl -L https://thetundra.com/interests/tech/groups/haskell-the-haskell-beginners-community
```

Here's the response:

```
HTTP/1.1 200 OK
Content-Type: text/html
Cache-Control: no-cache, no-store
Connection: close
Content-Length: 212
X-Iinfo: 9-256124937-0 0NNN RT(1625085245929 31) q(0 -1 -1 -1) r(0 -1) B10(8,881023,0) U5
Set-Cookie: visid_incap_2228506=plLd5eP7Q2axtfN2shU7eT3V3GAAAAAAQUIPAAAAAAD7yrXgNAba4CXiyfsVDqcT; expires=Thu, 30 Jun 2022 08:20:53 GMT; HttpOnly; path=/; Domain=.thetundra.com
Set-Cookie: incap_ses_532_2228506=/bDWQ2TMsx8pJL2UmQtiBz3V3GAAAAAARWGyoVLSE06BmISFGRFOfw==; path=/; Domain=.thetundra.com

<html>
<head>
<META NAME="robots" CONTENT="noindex,nofollow">
<script src="/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3">
</script>
<body>
</body></html>
```

**Comment by tomjaguarpaw** [comment]
Thanks for the diagnosis! I doubt it is worthwhile trying to find a way to get linkchecker to deal with this kind of thing :)

I will submit a PR to remove that link some time soon (or if anyone else wants to do so, they are welcome!).
